[tool.poetry]
name = "snowflake"
version = "0.1.0"
description = ""
authors = ["jojo <jonatha.ndamba.pro@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
dbt-snowflake = "^1.7.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
